/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamestopproject;
import java.awt.Desktop;
import java.io.*;
import java.io.InputStream;
import javax.swing.JOptionPane;

/**
 *
 * @author ethan
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jOptionPane1 = new javax.swing.JOptionPane();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ConButt = new javax.swing.JRadioButton();
        CaseButt = new javax.swing.JRadioButton();
        BagButt = new javax.swing.JRadioButton();
        ToyButt = new javax.swing.JRadioButton();
        MarioBox = new javax.swing.JCheckBox();
        HaloBox = new javax.swing.JCheckBox();
        PokeBox = new javax.swing.JCheckBox();
        DarkBox = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        XboxButt = new javax.swing.JRadioButton();
        PlayButt = new javax.swing.JRadioButton();
        NinButt = new javax.swing.JRadioButton();
        Totalfield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ClearButt = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        ExitButt = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        CheckOutButton = new javax.swing.JButton();
        EnterButton2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        GameButt1 = new javax.swing.JButton();
        GameButt2 = new javax.swing.JButton();
        GameButt3 = new javax.swing.JButton();
        GameButt4 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ethan\\Desktop\\Java Stuff\\GameStop Project\\GamestopProject\\gamestop-logo-png.png")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ethan\\Desktop\\Java Stuff\\GameStop Project\\GamestopProject\\Untitled (3).png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel2.setText("Here are today's Top Picks!");

        ConButt.setText("Controllers 40$");
        ConButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConButtActionPerformed(evt);
            }
        });

        CaseButt.setText("Game Case 10$");
        CaseButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaseButtActionPerformed(evt);
            }
        });

        BagButt.setText("Bag 5$");
        BagButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BagButtActionPerformed(evt);
            }
        });

        ToyButt.setText("Game Toy 10$");
        ToyButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToyButtActionPerformed(evt);
            }
        });

        MarioBox.setText("Witcher 3 Wild Hunt");
        MarioBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarioBoxActionPerformed(evt);
            }
        });

        HaloBox.setText("Halo MCC 25$");

        PokeBox.setText("At Dead Of Night 12$");

        DarkBox.setText("Hollow Knight 20$");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel6.setForeground(java.awt.Color.red);
        jLabel6.setText("Games");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel7.setForeground(java.awt.Color.red);
        jLabel7.setText("Extras");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel8.setForeground(java.awt.Color.red);
        jLabel8.setText("Consoles");

        XboxButt.setText("Xbox 500$");
        XboxButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XboxButtActionPerformed(evt);
            }
        });

        PlayButt.setText("Playstation 500$");
        PlayButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtActionPerformed(evt);
            }
        });

        NinButt.setText("Nintendo 350$");
        NinButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NinButtActionPerformed(evt);
            }
        });

        Totalfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalfieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Total:");

        ClearButt.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        ClearButt.setText("Clear");
        ClearButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtActionPerformed(evt);
            }
        });

        ExitButt.setText("Exit");
        ExitButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("$");

        CheckOutButton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        CheckOutButton.setText("Check Out!");
        CheckOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutButtonActionPerformed(evt);
            }
        });

        EnterButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        EnterButton2.setText("Enter");
        EnterButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterButton2ActionPerformed(evt);
            }
        });

        jButton2.setText("Ethan Berman");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        GameButt1.setText("Try Me!");
        GameButt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameButt1ActionPerformed(evt);
            }
        });

        GameButt2.setText("Try Me!");
        GameButt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameButt2ActionPerformed(evt);
            }
        });

        GameButt3.setText("Try Me!");
        GameButt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameButt3ActionPerformed(evt);
            }
        });

        GameButt4.setText("Try Me!");
        GameButt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameButt4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(PokeBox)
                                                    .addComponent(DarkBox))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(GameButt4)
                                                    .addComponent(GameButt3)))
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 36, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(MarioBox)
                                            .addComponent(HaloBox))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(GameButt1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(GameButt2)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BagButt)
                                    .addComponent(ToyButt)
                                    .addComponent(CaseButt)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ConButt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(XboxButt)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PlayButt)
                                    .addComponent(NinButt)))
                            .addComponent(CheckOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(Totalfield, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(EnterButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ClearButt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(ExitButt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(XboxButt)
                                .addGap(18, 18, 18)
                                .addComponent(PlayButt)
                                .addGap(18, 18, 18)
                                .addComponent(NinButt))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MarioBox)
                                    .addComponent(GameButt1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(HaloBox)
                                    .addComponent(GameButt2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PokeBox)
                                    .addComponent(GameButt3))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DarkBox)
                                    .addComponent(GameButt4)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ConButt)
                                .addGap(18, 18, 18)
                                .addComponent(CaseButt)
                                .addGap(18, 18, 18)
                                .addComponent(BagButt)
                                .addGap(20, 20, 20)
                                .addComponent(ToyButt)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(ClearButt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EnterButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Totalfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addComponent(CheckOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExitButt)
                        .addGap(3, 3, 3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MarioBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarioBoxActionPerformed
        // selects mario option
        
    }//GEN-LAST:event_MarioBoxActionPerformed

    private void ConButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConButtActionPerformed
        // Controller Variable
        if(ConButt.isSelected())
           CaseButt.setSelected(false);
            BagButt.setSelected(false);
            ToyButt.setSelected(false);
    }//GEN-LAST:event_ConButtActionPerformed

    private void CaseButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaseButtActionPerformed
       // Case Variable
        if(CaseButt.isSelected())
           ConButt.setSelected(false);
            BagButt.setSelected(false);
            ToyButt.setSelected(false);
    }//GEN-LAST:event_CaseButtActionPerformed

    private void BagButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagButtActionPerformed
        // Bag Variable
         if(BagButt.isSelected())
           CaseButt.setSelected(false);
            ConButt.setSelected(false);
            ToyButt.setSelected(false);
    }//GEN-LAST:event_BagButtActionPerformed

    private void ToyButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToyButtActionPerformed
        // Toy Variable
         if(ToyButt.isSelected())
           CaseButt.setSelected(false);
            BagButt.setSelected(false);
            ConButt.setSelected(false);
    }//GEN-LAST:event_ToyButtActionPerformed

    private void XboxButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XboxButtActionPerformed
        // Xbox Option
        if(XboxButt.isSelected())
           PlayButt.setSelected(false);
            NinButt.setSelected(false);
           
    }//GEN-LAST:event_XboxButtActionPerformed

    private void PlayButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtActionPerformed
        // PlayStation Option
        
        if(PlayButt.isSelected())
           XboxButt.setSelected(false);
            NinButt.setSelected(false);
           
    }//GEN-LAST:event_PlayButtActionPerformed

    private void NinButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NinButtActionPerformed
        // Nintendo Button:
        if(NinButt.isSelected())
           XboxButt.setSelected(false);
            PlayButt.setSelected(false);
    }//GEN-LAST:event_NinButtActionPerformed

    private void ClearButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtActionPerformed
     //Clear Button;
     
     MarioBox.setSelected(false);
     HaloBox.setSelected(false);
     PokeBox.setSelected(false);
     DarkBox.setSelected(false);
     ConButt.setSelected(false);
     CaseButt.setSelected(false);
     ToyButt.setSelected(false);
     BagButt.setSelected(false);
     XboxButt.setSelected(false);
     PlayButt.setSelected(false);
     NinButt.setSelected(false);
     
     int total=0;
     
     Totalfield.setText(Double.toString(total));
    }//GEN-LAST:event_ClearButtActionPerformed

    private void ExitButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtActionPerformed
        // Exit Button
        
        System.exit(0);
    }//GEN-LAST:event_ExitButtActionPerformed

    private void CheckOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutButtonActionPerformed
       int checkchoice = JOptionPane.showConfirmDialog(this,"Complete the Order?","Confirm",JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(checkchoice==JOptionPane.YES_OPTION){
            System.exit(0);
        }
       
        
    }//GEN-LAST:event_CheckOutButtonActionPerformed

    private void TotalfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalfieldActionPerformed

    private void EnterButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterButton2ActionPerformed
          // Enter Button:
        double total=0.0;
        
        // set up so that each value is added based on choices.
        if(MarioBox.isSelected()){
            total = total + 20;
        }
         if(HaloBox.isSelected()){
            total = total + 25;
        }
         if(PokeBox.isSelected()){
            total = total + 12;
        }
        if(DarkBox.isSelected()){
            total = total + 20;
        }
        
        //Optional 
        
         if(ConButt.isSelected()){
            total = total + 40;
        }
         if(CaseButt.isSelected()){
            total = total + 10;
        }
         if(BagButt.isSelected()){
            total = total + 5;
        }
        if(ToyButt.isSelected()){
            total = total + 10;
        }
        
        
        //Consoles
        
        if(XboxButt.isSelected()){
            total = total + 500;
        }
        if(PlayButt.isSelected()){
            total = total + 500;
        }
         if(NinButt.isSelected()){
            total = total + 350;
        }
        Totalfield.setText(Double.toString(total));
    }//GEN-LAST:event_EnterButton2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        try{
            File file = new File ("C:\\Users\\ethan\\Desktop\\jproj\\yOuRe fInAlLy aWaKe.mp4");
            if(file.exists()){
                if(Desktop.isDesktopSupported()){
                    Desktop.getDesktop().open(file);
                }else{
                    JOptionPane.showMessageDialog(this,"Not Supported!");
                }
            }else{
                JOptionPane.showMessageDialog(this,"File Not Found!");
            } 
        }catch (Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void GameButt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameButt1ActionPerformed
        try{
            File file = new File ("C:\\Users\\ethan\\Desktop\\The Witcher 3 Wild Hunt.url");
            if(file.exists()){
                if(Desktop.isDesktopSupported()){
                    Desktop.getDesktop().open(file);
                }else{
                    JOptionPane.showMessageDialog(this,"Not Supported!");
                }
            }else{
                JOptionPane.showMessageDialog(this,"File Not Found!");
            } 
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_GameButt1ActionPerformed

    private void GameButt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameButt2ActionPerformed
        try{
            File file = new File ("C:\\Users\\ethan\\Desktop\\Halo The Master Chief Collection.url");
            if(file.exists()){
                if(Desktop.isDesktopSupported()){
                    Desktop.getDesktop().open(file);
                }else{
                    JOptionPane.showMessageDialog(this,"Not Supported!");
                }
            }else{
                JOptionPane.showMessageDialog(this,"File Not Found!");
            } 
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_GameButt2ActionPerformed

    private void GameButt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameButt3ActionPerformed
        try{
            File file = new File ("C:\\Users\\ethan\\Desktop\\At Dead Of Night.url");
            if(file.exists()){
                if(Desktop.isDesktopSupported()){
                    Desktop.getDesktop().open(file);
                }else{
                    JOptionPane.showMessageDialog(this,"Not Supported!");
                }
            }else{
                JOptionPane.showMessageDialog(this,"File Not Found!");
            } 
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_GameButt3ActionPerformed

    private void GameButt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameButt4ActionPerformed
       try{
            File file = new File ("C:\\Users\\ethan\\Desktop\\Hollow Knight.url");
            if(file.exists()){
                if(Desktop.isDesktopSupported()){
                    Desktop.getDesktop().open(file);
                }else{
                    JOptionPane.showMessageDialog(this,"Not Supported!");
                }
            }else{
                JOptionPane.showMessageDialog(this,"File Not Found!");
            } 
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_GameButt4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BagButt;
    private javax.swing.JRadioButton CaseButt;
    private javax.swing.JButton CheckOutButton;
    private javax.swing.JButton ClearButt;
    private javax.swing.JRadioButton ConButt;
    private javax.swing.JCheckBox DarkBox;
    private javax.swing.JButton EnterButton2;
    private javax.swing.JButton ExitButt;
    private javax.swing.JButton GameButt1;
    private javax.swing.JButton GameButt2;
    private javax.swing.JButton GameButt3;
    private javax.swing.JButton GameButt4;
    private javax.swing.JCheckBox HaloBox;
    private javax.swing.JCheckBox MarioBox;
    private javax.swing.JRadioButton NinButt;
    private javax.swing.JRadioButton PlayButt;
    private javax.swing.JCheckBox PokeBox;
    private javax.swing.JTextField Totalfield;
    private javax.swing.JRadioButton ToyButt;
    private javax.swing.JRadioButton XboxButt;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
